export const sampleResponse = {
  Id: 9715,
  VaultId: 147,
  Name: "edgar-nKC772R_qog-unsplash.jpg",
  CanBeDownloaded: null,
  MediaConversions: [
    {
      Width: 2853,
      Height: 3803,
      AspectRatio: 0.7501972127267946,
      FormatWidth: 0,
      FormatHeight: 0,
      FormatAspectRatio: 0,
      MediaFormatName: "Original",
      Id: 9715,
      MediaFormatId: 1,
      Url: "https://iv-demo.imagevault.se/publishedmedia/t0vkx4r9l663noppm9vw/edgar-nKC772R_qog-unsplash.jpg",
      ContentDisplayType: 0,
      Html: '<img src="https://iv-demo.imagevault.se/publishedmedia/t0vkx4r9l663noppm9vw/edgar-nKC772R_qog-unsplash.jpg" alt width="2853" height="3803"/>',
      ContentType: "image/jpeg",
      Name: "edgar-nKC772R_qog-unsplash.jpg",
      DisplayInformation: null,
      IsFileIcon: false,
      RendererId: "F8C54BCD-3B8C-4C63-B6C7-302FA9BA8765",
      RendererData: null,
    },
  ],
  Metadata: [],
  Categories: null,
  Agreements: null,
  PublishInformation: null,
  DateAdded: "2022-02-01T14:05:07.663",
  Access: 0,
  AddedBy: "epipartner",
  Shared: false,
  DuplicateMediaItemId: null,
  DuplicateVersionId: null,
  CurrentVersionId: 4797,
  VersionId: 4797,
  MediaVersion: null,
  State: 2,
  DeletedDate: null,
};
